### ISSUE TITLE
启动zookeeper失败

### ISSUE THREAD

**Issue by iven-j** [youngyangyang04/RPC-Java#11]
哥直接copy的代码，启动version1 part3的时候，testclient报错，请问是需要改rootpath吗
![image](https://github.com/user-attachments/assets/64fea447-a2e5-40b2-a05c-e3276eb541f7)

**Comment by iven-j** [comment]
> 哥直接copy的代码，启动version1 part3的时候，testclient报错，请问是需要改rootpath吗 ![image](https://private-user-images.githubusercontent.com/100260319/349005960-64fea447-a2e5-40b2-a05c-e3276eb541f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDkwNTAsIm5iZiI6MTcyMTIwODc1MCwicGF0aCI6Ii8xMDAyNjAzMTkvMzQ5MDA1OTYwLTY0ZmVhNDQ3LWEyZTUtNDBiMi1hMDVjLWUzMjc2ZWI1NDFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwOTMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjYwYmE2OWQyYzMzZmEwZWNkYWVhNmMxYThkMTVhM2ExZWZhODc5MmNjNTgxOTQxMDc4Y2U5MDM5YjA2ODg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._cD3a20Pv2p0vQk9CmL33WX0Esfq1qFCd0RIvoXM9rc)

已解决 zookeeper与crutor的版本冲突，curator-recipes版本号为5.1.0，对应zookeeper版本要3.6以上

**Comment by GGBoooond** [comment]
感谢补充

**Comment by GGBoooond** [comment]
感谢补充，我在文档中修改一下对应zk的安装教程

**Comment by yunhuaCN** [comment]
zookeeper版本3.6.4，curator版本5.1.0，在运行Client的时候依然报错
`org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /D:/coding/javaprojects/myRPC/src/main/java/common.service.UserService
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2847)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:242)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:231)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:228)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:219)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:41)
	at Client.serviceCenter.ZKServiceCenter.serviceDiscovery(ZKServiceCenter.java:45)
	at Client.rpcClient.Impl.NettyRpcClient.sendRequest(NettyRpcClient.java:46)
	at Client.proxy.ClientProxy.invoke(ClientProxy.java:34)
	at jdk.proxy2/jdk.proxy2.$Proxy5.getUserByUserId(Unknown Source)
	at Client.TestClient.main(TestClient.java:14)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getHostName()" because "address" is null
	at Client.rpcClient.Impl.NettyRpcClient.sendRequest(NettyRpcClient.java:47)
	at Client.proxy.ClientProxy.invoke(ClientProxy.java:34)
	at jdk.proxy2/jdk.proxy2.$Proxy5.getUserByUserId(Unknown Source)
	at Client.TestClient.main(TestClient.java:14)`


使用cmd打开zookeeper的server显示：

![Image](https://github.com/user-attachments/assets/a9a13ce9-ac9c-49b0-b09f-d93e2c5d207e)
